# Generated by Django 2.1.4 on 2019-11-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50000, null=True)),
                ('emotion', models.IntegerField(null=True)),
                ('is_agriculture', models.IntegerField(null=True)),
                ('keywords', models.CharField(max_length=50, null=True)),
                ('publish_time', models.CharField(max_length=50, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('summary', models.CharField(max_length=5000, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=500, null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('product_name', models.CharField(max_length=500, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_start_url', models.CharField(max_length=255, null=True)),
                ('web_name', models.CharField(max_length=255, null=True)),
                ('level_1', models.CharField(max_length=255, null=True)),
                ('level_2', models.CharField(max_length=255, null=True)),
                ('level_3', models.CharField(max_length=255, null=True)),
                ('crawl_max_page', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, max_length=255, null=True)),
                ('end', models.CharField(blank=True, max_length=255, null=True)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('min_times', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('is_use', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductNameToCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyname', models.CharField(max_length=255, null=True)),
                ('product_name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
